services:
  api:
    build: ./backend
    container_name: api_postermaker
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             gunicorn postermaker.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      DJANGO_SECRET_KEY: "change_me"
  web:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:8000/api"
    container_name: app_postermaker
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - api

